baseURL         = 'http://192.168.0.21:8000/'
languageCode    = 'en-us'
title           = 'Lucas Elvira-Martin CV'


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)']]

    [markup.highlight]
        codeFences = false
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 2
        noClasses = false
        style = 'dracula'
    [markup.tableOfContents]
        ordered = false
        startLevel = 2
        endLevel = 3


[menus]
    [[menus.main]]
        name    = 'CV'
        pageRef = '/cv'
        url     = '/cv'
        weight  = 2
        identifier = 'CV'
    [[menus.main]]
        name    = 'Experience'
        url     = '#experience'
        weight  = 2
        parent = 'CV'
    [[menus.main]]
        name    = 'Education'
        url     = '/cv/#education'
        parent = 'CV'
        weight  = 3

[params]
    math = true
    description = 'Discover innovative software development projects, practical tutorials, and insights from a passionate software engineer dedicated to solving real-world challenges.'
        
[taxonomies]
    category    = 'categories'
    tag         = 'tags'
    project     = 'projects'
    author      = 'author'
    post        = 'posts'
