baseURL         = 'http://192.168.0.21:8000/'
languageCode    = 'en-us'
title           = 'Lucas Elvira-Martin CV'


[markup]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.highlight]
        codeFences = false
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 2
        noClasses = false
        style = 'dracula'

[menus]
#    [[menus.main]]
#        name    = 'Home'
#        pageRef = '/'
#        url     = '/'
#        weight  = 1
    [[menus.main]]
        name    = 'CV'
        pageRef = '/cv'
        url     = '/cv'
        weight  = 2
#    [[menus.main]]
#        name    = 'Projects'
#        pageRef = '/projects'
#        url = '/projects'
#        identifier = 'projects'
#        weight  = 3
#    [[menus.main]]
#        name    = 'Blog'
#        identifier = 'The Blog'
#        pageRef = '/posts'
#        url     = '/posts'
#        weight  = 4
    [[menus.about]]
        name    = 'Experience'
        url     = '/#experience'
        weight  = 2
    [[menus.about]]
        name    = 'Education'
        url     = '/#education'
        weight  = 3
        
[taxonomies]
    category    = 'categories'
    tag         = 'tags'
    project     = 'projects'
    author      = 'author'
    post        = 'posts'
